### ISSUE TITLE
EPIC: Just get Minion working

### ISSUE THREAD

**Issue by gjersvik** [equinor/eit-robotic-avatar-two#36]
- [x] Move over old minion client code from [eit-robotic-avatar](https://github.com/equinor/eit-robotic-avata).
- [x] #40
- [x] Port old server to minion module.
- [x] Old client into minion client.
- [x] Get video working.
- [x] Get arm working.
- [x] #56
- [x] #76
