### ISSUE TITLE
EPIC: Minion resurrection 

### ISSUE THREAD

**Issue by gjersvik** [equinor/eit-robotic-avatar-two#9]
Do what needs to be done to have new minion robot driving with new software.

## Communications
- [x] #30
- [x] #45
- [x] #24
- [ ] Authorization.
- [x] #20
- [ ] Browser WebRTC
- [ ] Browser-less WebRTC

## Driving
- [ ] VR-Controller input.
- [ ] Motor Controller.
- [ ] Driving input to motor.

## Robotic neck
- [ ] Headset tracking.
- [ ] Robot-arm Controller
- [ ] Headset to arm.

## Robotic eyes
- [ ] Camera Controller
- [ ] Web XR viewport
- [ ] Video over WebRTC

## Audio
- [ ] Robot Mic Speaker Controller
- [ ] Headset Mic Speaker.
- [ ] Audio over WebRTC.

## Other
- [x] #22
- [x] #40
- [ ] Minion startup and deploy scripts.
- [x] #10

**Comment by gjersvik** [comment]
Old plan not really valid anymore.
